# Generated by Django 3.2.7 on 2021-09-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0004_tests_decimal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testmodel",
            name="year_in_school",
        ),
    ]
