# Generated by Django 4.0.3 on 2022-03-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0005_remove_testmodel_year_in_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testmodel",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="testmodel",
            name="name",
            field=models.CharField(max_length=200, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="testmodel",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.AlterField(
            model_name="testmodelpk",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="testmodelpk",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
    ]
