# Generated by Django 4.1 on 2022-08-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0006_alter_testmodel_created_alter_testmodel_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testmodel",
            name="datalist",
            field=models.CharField(default="Hey", max_length=30),
            preserve_default=False,
        ),
    ]
