name: Release on GitHub & PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install -U poetry twine wheel
      - run: poetry build
      - run: twine upload --non-interactive -u __token__ -p ${{ secrets.PYPI_TOKEN }} dist/*
      - env:
          TAG: ${GITHUB_REF#refs/tags/}
        run: gh release create -d -t "Release $TAG" -n $(awk "/## \[$TAG] - /{flag=1;next}/## \[/{flag=0}flag" CHANGELOG.md) $TAG dist/*
